trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureCLI@2
  inputs:
    azureSubscription: 'new'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |

      pwd

      ls -R

      wget https://releases.hashicorp.com/terraform/1.9.8/terraform_1.9.8_linux_amd64.zip

      unzip terraform_1.9.8_linux_amd64.zip

      sudo mv terraform /usr/local/bin/

      terraform version

      cd terraform

      terraform init
