trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: AzureCLI@2
  displayName: 'Terraform Deploy'
  inputs:
    azureSubscription: 'new'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |

      echo "===== Azure Account ====="
      az account show

      wget https://releases.hashicorp.com/terraform/1.9.8/terraform_1.9.8_linux_amd64.zip

      sudo apt-get update
      sudo apt-get install unzip -y

      unzip -o terraform_1.9.8_linux_amd64.zip

      sudo mv terraform /usr/local/bin/

      terraform version

      cd $(System.DefaultWorkingDirectory)/terraform

      echo "===== Terraform Files ====="
      ls -la

      terraform init

      terraform validate

      terraform plan -out=tfplan

      terraform show tfplan
